// Frontend_Development/handson_07/student-portal-angular/src/app/course-card/course-card.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-course-card',
  standalone: true,
  templateUrl: './course-card.html',
  styleUrl: './course-card.css'
})
export class CourseCard {

  @Input() name = '';
  @Input() code = '';
  @Input() credits = 0;
  @Input() grade = '';

}

// Frontend_Development/handson_05/student-portal-react/src/components/CourseCard.jsx
function CourseCard({
  id,
  name,
  code,
  credits,
  grade,
  onEnroll,
  isEnrolled,
}) {
  return (
    <div className="card">
      <div className="card-header">
        <h2>📘 {name}</h2>

        <span className="grade">
          Grade: <strong>{grade}</strong>
        </span>
      </div>

      <div className="course-info">
        <p>
          <strong>Course Code:</strong> {code}
        </p>

        <p>
          <strong>Credits:</strong> {credits}
        </p>
      </div>

      <button
        className={isEnrolled ? "btn enrolled" : "btn"}
        disabled={isEnrolled}
        onClick={() => onEnroll(id)}
      >
        {isEnrolled ? "✔ Enrolled" : "Enroll"}
      </button>
    </div>
  );
}

export default CourseCard;
